/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var school_pb = require('./school_pb.js');
goog.exportSymbol('proto.protobuffers.Create_Bid', null, global);
goog.exportSymbol('proto.protobuffers.Create_School', null, global);
goog.exportSymbol('proto.protobuffers.Method', null, global);
goog.exportSymbol('proto.protobuffers.RPCRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protobuffers.RPCRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.protobuffers.RPCRequest.oneofGroups_);
};
goog.inherits(proto.protobuffers.RPCRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protobuffers.RPCRequest.displayName = 'proto.protobuffers.RPCRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.protobuffers.RPCRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.protobuffers.RPCRequest.MethodCase = {
  METHOD_NOT_SET: 0,
  CREATE_SCHOOL: 1,
  CREATE_BID: 2
};

/**
 * @return {proto.protobuffers.RPCRequest.MethodCase}
 */
proto.protobuffers.RPCRequest.prototype.getMethodCase = function() {
  return /** @type {proto.protobuffers.RPCRequest.MethodCase} */(jspb.Message.computeOneofCase(this, proto.protobuffers.RPCRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protobuffers.RPCRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.protobuffers.RPCRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protobuffers.RPCRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.RPCRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    createSchool: (f = msg.getCreateSchool()) && proto.protobuffers.Create_School.toObject(includeInstance, f),
    createBid: (f = msg.getCreateBid()) && proto.protobuffers.Create_Bid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protobuffers.RPCRequest}
 */
proto.protobuffers.RPCRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protobuffers.RPCRequest;
  return proto.protobuffers.RPCRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protobuffers.RPCRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protobuffers.RPCRequest}
 */
proto.protobuffers.RPCRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.protobuffers.Create_School;
      reader.readMessage(value,proto.protobuffers.Create_School.deserializeBinaryFromReader);
      msg.setCreateSchool(value);
      break;
    case 2:
      var value = new proto.protobuffers.Create_Bid;
      reader.readMessage(value,proto.protobuffers.Create_Bid.deserializeBinaryFromReader);
      msg.setCreateBid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protobuffers.RPCRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protobuffers.RPCRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protobuffers.RPCRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.RPCRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreateSchool();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.protobuffers.Create_School.serializeBinaryToWriter
    );
  }
  f = message.getCreateBid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.protobuffers.Create_Bid.serializeBinaryToWriter
    );
  }
};


/**
 * optional Create_School create_school = 1;
 * @return {?proto.protobuffers.Create_School}
 */
proto.protobuffers.RPCRequest.prototype.getCreateSchool = function() {
  return /** @type{?proto.protobuffers.Create_School} */ (
    jspb.Message.getWrapperField(this, proto.protobuffers.Create_School, 1));
};


/** @param {?proto.protobuffers.Create_School|undefined} value */
proto.protobuffers.RPCRequest.prototype.setCreateSchool = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.protobuffers.RPCRequest.oneofGroups_[0], value);
};


proto.protobuffers.RPCRequest.prototype.clearCreateSchool = function() {
  this.setCreateSchool(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protobuffers.RPCRequest.prototype.hasCreateSchool = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Create_Bid create_bid = 2;
 * @return {?proto.protobuffers.Create_Bid}
 */
proto.protobuffers.RPCRequest.prototype.getCreateBid = function() {
  return /** @type{?proto.protobuffers.Create_Bid} */ (
    jspb.Message.getWrapperField(this, proto.protobuffers.Create_Bid, 2));
};


/** @param {?proto.protobuffers.Create_Bid|undefined} value */
proto.protobuffers.RPCRequest.prototype.setCreateBid = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.protobuffers.RPCRequest.oneofGroups_[0], value);
};


proto.protobuffers.RPCRequest.prototype.clearCreateBid = function() {
  this.setCreateBid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protobuffers.RPCRequest.prototype.hasCreateBid = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protobuffers.Create_School = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protobuffers.Create_School, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protobuffers.Create_School.displayName = 'proto.protobuffers.Create_School';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protobuffers.Create_School.prototype.toObject = function(opt_includeInstance) {
  return proto.protobuffers.Create_School.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protobuffers.Create_School} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.Create_School.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && school_pb.School.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protobuffers.Create_School}
 */
proto.protobuffers.Create_School.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protobuffers.Create_School;
  return proto.protobuffers.Create_School.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protobuffers.Create_School} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protobuffers.Create_School}
 */
proto.protobuffers.Create_School.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new school_pb.School;
      reader.readMessage(value,school_pb.School.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protobuffers.Create_School.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protobuffers.Create_School.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protobuffers.Create_School} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.Create_School.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      school_pb.School.serializeBinaryToWriter
    );
  }
};


/**
 * optional School params = 1;
 * @return {?proto.protobuffers.School}
 */
proto.protobuffers.Create_School.prototype.getParams = function() {
  return /** @type{?proto.protobuffers.School} */ (
    jspb.Message.getWrapperField(this, school_pb.School, 1));
};


/** @param {?proto.protobuffers.School|undefined} value */
proto.protobuffers.Create_School.prototype.setParams = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.protobuffers.Create_School.prototype.clearParams = function() {
  this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protobuffers.Create_School.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protobuffers.Create_Bid = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.protobuffers.Create_Bid.repeatedFields_, null);
};
goog.inherits(proto.protobuffers.Create_Bid, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protobuffers.Create_Bid.displayName = 'proto.protobuffers.Create_Bid';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.protobuffers.Create_Bid.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protobuffers.Create_Bid.prototype.toObject = function(opt_includeInstance) {
  return proto.protobuffers.Create_Bid.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protobuffers.Create_Bid} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.Create_Bid.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressesList: jspb.Message.getRepeatedField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protobuffers.Create_Bid}
 */
proto.protobuffers.Create_Bid.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protobuffers.Create_Bid;
  return proto.protobuffers.Create_Bid.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protobuffers.Create_Bid} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protobuffers.Create_Bid}
 */
proto.protobuffers.Create_Bid.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddresses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protobuffers.Create_Bid.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protobuffers.Create_Bid.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protobuffers.Create_Bid} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuffers.Create_Bid.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string addresses = 1;
 * @return {!Array<string>}
 */
proto.protobuffers.Create_Bid.prototype.getAddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.protobuffers.Create_Bid.prototype.setAddressesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.protobuffers.Create_Bid.prototype.addAddresses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.protobuffers.Create_Bid.prototype.clearAddressesList = function() {
  this.setAddressesList([]);
};


/**
 * @enum {number}
 */
proto.protobuffers.Method = {
  CREATE_SCHOOL: 0,
  CREATE_BID: 1
};

goog.object.extend(exports, proto.protobuffers);
