// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_methods.proto

package protobuffers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_CREATE_SCHOOL Method = 0
	Method_CREATE_BID    Method = 1
)

var Method_name = map[int32]string{
	0: "CREATE_SCHOOL",
	1: "CREATE_BID",
}
var Method_value = map[string]int32{
	"CREATE_SCHOOL": 0,
	"CREATE_BID":    1,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpc_methods_6a377331092f600d, []int{0}
}

type RPCRequest struct {
	// Types that are valid to be assigned to Method:
	//	*RPCRequest_CreateSchool
	//	*RPCRequest_CreateBid
	Method               isRPCRequest_Method `protobuf_oneof:"method"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_methods_6a377331092f600d, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (dst *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(dst, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

type isRPCRequest_Method interface {
	isRPCRequest_Method()
}

type RPCRequest_CreateSchool struct {
	CreateSchool *Create_School `protobuf:"bytes,1,opt,name=create_school,json=createSchool,proto3,oneof"`
}

type RPCRequest_CreateBid struct {
	CreateBid *Create_Bid `protobuf:"bytes,2,opt,name=create_bid,json=createBid,proto3,oneof"`
}

func (*RPCRequest_CreateSchool) isRPCRequest_Method() {}

func (*RPCRequest_CreateBid) isRPCRequest_Method() {}

func (m *RPCRequest) GetMethod() isRPCRequest_Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *RPCRequest) GetCreateSchool() *Create_School {
	if x, ok := m.GetMethod().(*RPCRequest_CreateSchool); ok {
		return x.CreateSchool
	}
	return nil
}

func (m *RPCRequest) GetCreateBid() *Create_Bid {
	if x, ok := m.GetMethod().(*RPCRequest_CreateBid); ok {
		return x.CreateBid
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RPCRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RPCRequest_OneofMarshaler, _RPCRequest_OneofUnmarshaler, _RPCRequest_OneofSizer, []interface{}{
		(*RPCRequest_CreateSchool)(nil),
		(*RPCRequest_CreateBid)(nil),
	}
}

func _RPCRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_CreateSchool:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateSchool); err != nil {
			return err
		}
	case *RPCRequest_CreateBid:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateBid); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RPCRequest.Method has unexpected type %T", x)
	}
	return nil
}

func _RPCRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RPCRequest)
	switch tag {
	case 1: // method.create_school
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Create_School)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_CreateSchool{msg}
		return true, err
	case 2: // method.create_bid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Create_Bid)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_CreateBid{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RPCRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_CreateSchool:
		s := proto.Size(x.CreateSchool)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RPCRequest_CreateBid:
		s := proto.Size(x.CreateBid)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Create_School struct {
	Params               *School  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Create_School) Reset()         { *m = Create_School{} }
func (m *Create_School) String() string { return proto.CompactTextString(m) }
func (*Create_School) ProtoMessage()    {}
func (*Create_School) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_methods_6a377331092f600d, []int{1}
}
func (m *Create_School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create_School.Unmarshal(m, b)
}
func (m *Create_School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create_School.Marshal(b, m, deterministic)
}
func (dst *Create_School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create_School.Merge(dst, src)
}
func (m *Create_School) XXX_Size() int {
	return xxx_messageInfo_Create_School.Size(m)
}
func (m *Create_School) XXX_DiscardUnknown() {
	xxx_messageInfo_Create_School.DiscardUnknown(m)
}

var xxx_messageInfo_Create_School proto.InternalMessageInfo

func (m *Create_School) GetParams() *School {
	if m != nil {
		return m.Params
	}
	return nil
}

type Create_Bid struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Create_Bid) Reset()         { *m = Create_Bid{} }
func (m *Create_Bid) String() string { return proto.CompactTextString(m) }
func (*Create_Bid) ProtoMessage()    {}
func (*Create_Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_methods_6a377331092f600d, []int{2}
}
func (m *Create_Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create_Bid.Unmarshal(m, b)
}
func (m *Create_Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create_Bid.Marshal(b, m, deterministic)
}
func (dst *Create_Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create_Bid.Merge(dst, src)
}
func (m *Create_Bid) XXX_Size() int {
	return xxx_messageInfo_Create_Bid.Size(m)
}
func (m *Create_Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Create_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Create_Bid proto.InternalMessageInfo

func (m *Create_Bid) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "protobuffers.RPCRequest")
	proto.RegisterType((*Create_School)(nil), "protobuffers.Create_School")
	proto.RegisterType((*Create_Bid)(nil), "protobuffers.Create_Bid")
	proto.RegisterEnum("protobuffers.Method", Method_name, Method_value)
}

func init() { proto.RegisterFile("rpc_methods.proto", fileDescriptor_rpc_methods_6a377331092f600d) }

var fileDescriptor_rpc_methods_6a377331092f600d = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x5b, 0x85, 0x62, 0x3f, 0x5b, 0xd9, 0x82, 0x87, 0xa2, 0x1e, 0xa4, 0xa7, 0x31, 0xa5,
	0x07, 0x3d, 0x79, 0xf0, 0x60, 0xea, 0xa0, 0x82, 0x32, 0xc9, 0xbc, 0x97, 0xb6, 0xc9, 0x58, 0xc1,
	0x91, 0x9a, 0x74, 0x7f, 0x8a, 0xff, 0xaf, 0x98, 0x17, 0x98, 0x03, 0x4f, 0x21, 0xef, 0xfd, 0xde,
	0xef, 0xfb, 0x30, 0x35, 0x43, 0x57, 0x6f, 0xd5, 0xb8, 0xd1, 0xd2, 0x16, 0x83, 0xd1, 0xa3, 0x66,
	0x89, 0x7b, 0xda, 0xdd, 0x7a, 0xad, 0x8c, 0xbd, 0x48, 0x6c, 0xb7, 0xd1, 0xfa, 0x93, 0x76, 0xf9,
	0x77, 0x08, 0x88, 0xf7, 0x52, 0xa8, 0xaf, 0x9d, 0xb2, 0x23, 0xe3, 0x48, 0x3b, 0xa3, 0x9a, 0x51,
	0xd5, 0x44, 0x65, 0xe1, 0x75, 0x38, 0x3b, 0xbd, 0xbb, 0x2c, 0xfe, 0x2a, 0x8a, 0x92, 0x90, 0x95,
	0x43, 0xaa, 0x40, 0x24, 0x74, 0x43, 0x7f, 0xf6, 0x00, 0x78, 0x47, 0xdb, 0xcb, 0xec, 0xc8, 0x09,
	0xb2, 0x7f, 0x05, 0xbc, 0x97, 0x55, 0x20, 0x62, 0xa2, 0x79, 0x2f, 0xf9, 0x09, 0x22, 0xaa, 0x9e,
	0x3f, 0x22, 0x3d, 0x48, 0x61, 0xb7, 0x88, 0x86, 0xc6, 0x34, 0x5b, 0xeb, 0x2b, 0x9d, 0x1f, 0x1a,
	0x89, 0x12, 0x9e, 0xc9, 0xe7, 0xc0, 0x3e, 0x83, 0x5d, 0x21, 0x6e, 0xa4, 0x34, 0xca, 0x5a, 0xf5,
	0x7b, 0x7e, 0x3c, 0x8b, 0xc5, 0x7e, 0x30, 0xbf, 0x41, 0xf4, 0xe6, 0x42, 0xd9, 0x14, 0x69, 0x29,
	0x16, 0x4f, 0x1f, 0x8b, 0x7a, 0x55, 0x56, 0xcb, 0xe5, 0xeb, 0x24, 0x60, 0x67, 0x80, 0x1f, 0xf1,
	0x97, 0xe7, 0x49, 0xd8, 0x46, 0x2e, 0xf5, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x04, 0x15,
	0x2e, 0x67, 0x01, 0x00, 0x00,
}
