// Code generated by protoc-gen-go. DO NOT EDIT.
// source: school.proto

package protobuffers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type School struct {
	EnsHost                  string   `protobuf:"bytes,65,opt,name=ens_host,json=ensHost,proto3" json:"ens_host,omitempty"`
	Address                  string   `protobuf:"bytes,55,opt,name=address,proto3" json:"address,omitempty"`
	Admin0                   string   `protobuf:"bytes,1,opt,name=admin0,proto3" json:"admin0,omitempty"`
	Admin1                   string   `protobuf:"bytes,2,opt,name=admin1,proto3" json:"admin1,omitempty"`
	Admin2                   string   `protobuf:"bytes,3,opt,name=admin2,proto3" json:"admin2,omitempty"`
	Admin3                   string   `protobuf:"bytes,4,opt,name=admin3,proto3" json:"admin3,omitempty"`
	Admin4                   string   `protobuf:"bytes,5,opt,name=admin4,proto3" json:"admin4,omitempty"`
	AdminCode                string   `protobuf:"bytes,6,opt,name=admin_code,json=adminCode,proto3" json:"admin_code,omitempty"`
	AdminId                  string   `protobuf:"bytes,7,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Altitude                 string   `protobuf:"bytes,8,opt,name=altitude,proto3" json:"altitude,omitempty"`
	AvailabilityConnectivity string   `protobuf:"bytes,9,opt,name=availability_connectivity,json=availabilityConnectivity,proto3" json:"availability_connectivity,omitempty"`
	Connectivity             string   `protobuf:"bytes,10,opt,name=connectivity,proto3" json:"connectivity,omitempty"`
	CountryCode              string   `protobuf:"bytes,11,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Datasource               string   `protobuf:"bytes,12,opt,name=datasource,proto3" json:"datasource,omitempty"`
	Description              string   `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	EducLevel                string   `protobuf:"bytes,14,opt,name=educ_level,json=educLevel,proto3" json:"educ_level,omitempty"`
	Electricity              string   `protobuf:"bytes,15,opt,name=electricity,proto3" json:"electricity,omitempty"`
	Environment              string   `protobuf:"bytes,16,opt,name=environment,proto3" json:"environment,omitempty"`
	Frequency                string   `protobuf:"bytes,17,opt,name=frequency,proto3" json:"frequency,omitempty"`
	LatencyConnectivity      string   `protobuf:"bytes,18,opt,name=latency_connectivity,json=latencyConnectivity,proto3" json:"latency_connectivity,omitempty"`
	Lat                      string   `protobuf:"bytes,19,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                      string   `protobuf:"bytes,20,opt,name=lon,proto3" json:"lon,omitempty"`
	Name                     string   `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	NumClassrooms            string   `protobuf:"bytes,22,opt,name=num_classrooms,json=numClassrooms,proto3" json:"num_classrooms,omitempty"`
	NumLatrines              string   `protobuf:"bytes,23,opt,name=num_latrines,json=numLatrines,proto3" json:"num_latrines,omitempty"`
	NumTeachers              string   `protobuf:"bytes,24,opt,name=num_teachers,json=numTeachers,proto3" json:"num_teachers,omitempty"`
	NumStudents              string   `protobuf:"bytes,25,opt,name=num_students,json=numStudents,proto3" json:"num_students,omitempty"`
	NumSections              string   `protobuf:"bytes,26,opt,name=num_sections,json=numSections,proto3" json:"num_sections,omitempty"`
	PhoneNumber              string   `protobuf:"bytes,27,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PostalCode               string   `protobuf:"bytes,28,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	SpeedConnectivity        string   `protobuf:"bytes,29,opt,name=speed_connectivity,json=speedConnectivity,proto3" json:"speed_connectivity,omitempty"`
	TypeConnectivity         string   `protobuf:"bytes,30,opt,name=type_connectivity,json=typeConnectivity,proto3" json:"type_connectivity,omitempty"`
	TypeSchool               string   `protobuf:"bytes,31,opt,name=type_school,json=typeSchool,proto3" json:"type_school,omitempty"`
	Water                    string   `protobuf:"bytes,32,opt,name=water,proto3" json:"water,omitempty"`
	CreatedAt                string   `protobuf:"bytes,33,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                string   `protobuf:"bytes,34,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProbeId                  string   `protobuf:"bytes,35,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeProvider            string   `protobuf:"bytes,36,opt,name=probe_provider,json=probeProvider,proto3" json:"probe_provider,omitempty"`
	IspId                    string   `protobuf:"bytes,37,opt,name=isp_id,json=ispId,proto3" json:"isp_id,omitempty"`
	SchoolId                 string   `protobuf:"bytes,38,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	Id_0                     string   `protobuf:"bytes,39,opt,name=id_0,json=id0,proto3" json:"id_0,omitempty"`
	Id_1                     string   `protobuf:"bytes,40,opt,name=id_1,json=id1,proto3" json:"id_1,omitempty"`
	Id_2                     string   `protobuf:"bytes,41,opt,name=id_2,json=id2,proto3" json:"id_2,omitempty"`
	Id_3                     string   `protobuf:"bytes,42,opt,name=id_3,json=id3,proto3" json:"id_3,omitempty"`
	Id_4                     string   `protobuf:"bytes,43,opt,name=id_4,json=id4,proto3" json:"id_4,omitempty"`
	Id_5                     string   `protobuf:"bytes,44,opt,name=id_5,json=id5,proto3" json:"id_5,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_ae798327a1a55510, []int{0}
}
func (m *School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_School.Unmarshal(m, b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_School.Marshal(b, m, deterministic)
}
func (dst *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(dst, src)
}
func (m *School) XXX_Size() int {
	return xxx_messageInfo_School.Size(m)
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetEnsHost() string {
	if m != nil {
		return m.EnsHost
	}
	return ""
}

func (m *School) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *School) GetAdmin0() string {
	if m != nil {
		return m.Admin0
	}
	return ""
}

func (m *School) GetAdmin1() string {
	if m != nil {
		return m.Admin1
	}
	return ""
}

func (m *School) GetAdmin2() string {
	if m != nil {
		return m.Admin2
	}
	return ""
}

func (m *School) GetAdmin3() string {
	if m != nil {
		return m.Admin3
	}
	return ""
}

func (m *School) GetAdmin4() string {
	if m != nil {
		return m.Admin4
	}
	return ""
}

func (m *School) GetAdminCode() string {
	if m != nil {
		return m.AdminCode
	}
	return ""
}

func (m *School) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *School) GetAltitude() string {
	if m != nil {
		return m.Altitude
	}
	return ""
}

func (m *School) GetAvailabilityConnectivity() string {
	if m != nil {
		return m.AvailabilityConnectivity
	}
	return ""
}

func (m *School) GetConnectivity() string {
	if m != nil {
		return m.Connectivity
	}
	return ""
}

func (m *School) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *School) GetDatasource() string {
	if m != nil {
		return m.Datasource
	}
	return ""
}

func (m *School) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *School) GetEducLevel() string {
	if m != nil {
		return m.EducLevel
	}
	return ""
}

func (m *School) GetElectricity() string {
	if m != nil {
		return m.Electricity
	}
	return ""
}

func (m *School) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *School) GetFrequency() string {
	if m != nil {
		return m.Frequency
	}
	return ""
}

func (m *School) GetLatencyConnectivity() string {
	if m != nil {
		return m.LatencyConnectivity
	}
	return ""
}

func (m *School) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *School) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *School) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *School) GetNumClassrooms() string {
	if m != nil {
		return m.NumClassrooms
	}
	return ""
}

func (m *School) GetNumLatrines() string {
	if m != nil {
		return m.NumLatrines
	}
	return ""
}

func (m *School) GetNumTeachers() string {
	if m != nil {
		return m.NumTeachers
	}
	return ""
}

func (m *School) GetNumStudents() string {
	if m != nil {
		return m.NumStudents
	}
	return ""
}

func (m *School) GetNumSections() string {
	if m != nil {
		return m.NumSections
	}
	return ""
}

func (m *School) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *School) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *School) GetSpeedConnectivity() string {
	if m != nil {
		return m.SpeedConnectivity
	}
	return ""
}

func (m *School) GetTypeConnectivity() string {
	if m != nil {
		return m.TypeConnectivity
	}
	return ""
}

func (m *School) GetTypeSchool() string {
	if m != nil {
		return m.TypeSchool
	}
	return ""
}

func (m *School) GetWater() string {
	if m != nil {
		return m.Water
	}
	return ""
}

func (m *School) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *School) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *School) GetProbeId() string {
	if m != nil {
		return m.ProbeId
	}
	return ""
}

func (m *School) GetProbeProvider() string {
	if m != nil {
		return m.ProbeProvider
	}
	return ""
}

func (m *School) GetIspId() string {
	if m != nil {
		return m.IspId
	}
	return ""
}

func (m *School) GetSchoolId() string {
	if m != nil {
		return m.SchoolId
	}
	return ""
}

func (m *School) GetId_0() string {
	if m != nil {
		return m.Id_0
	}
	return ""
}

func (m *School) GetId_1() string {
	if m != nil {
		return m.Id_1
	}
	return ""
}

func (m *School) GetId_2() string {
	if m != nil {
		return m.Id_2
	}
	return ""
}

func (m *School) GetId_3() string {
	if m != nil {
		return m.Id_3
	}
	return ""
}

func (m *School) GetId_4() string {
	if m != nil {
		return m.Id_4
	}
	return ""
}

func (m *School) GetId_5() string {
	if m != nil {
		return m.Id_5
	}
	return ""
}

func init() {
	proto.RegisterType((*School)(nil), "protobuffers.School")
}

func init() { proto.RegisterFile("school.proto", fileDescriptor_school_ae798327a1a55510) }

var fileDescriptor_school_ae798327a1a55510 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x94, 0x49, 0x6f, 0xdb, 0x38,
	0x14, 0xc7, 0x91, 0x49, 0xe2, 0xc4, 0xb4, 0x93, 0x89, 0x99, 0x65, 0x5e, 0xf6, 0x65, 0x26, 0xd3,
	0xb4, 0x69, 0x8b, 0x78, 0x09, 0x7a, 0xe8, 0x29, 0xc8, 0xa5, 0x06, 0x82, 0xa2, 0x68, 0x7a, 0x17,
	0x68, 0xf1, 0x05, 0x26, 0x20, 0x91, 0x2a, 0x49, 0xb9, 0xf0, 0x87, 0xee, 0x77, 0x28, 0xb8, 0x48,
	0x91, 0x4e, 0x26, 0x7f, 0xff, 0x9f, 0x25, 0xf2, 0xe9, 0x91, 0xa4, 0x6f, 0xd2, 0xb9, 0x52, 0xd9,
	0xc7, 0x42, 0x2b, 0xab, 0x68, 0xdf, 0xff, 0xcc, 0xca, 0x97, 0x17, 0xd4, 0xe6, 0xea, 0x37, 0x21,
	0x9d, 0x67, 0x1f, 0xd3, 0x43, 0xb2, 0x89, 0xd2, 0x24, 0x73, 0x65, 0x2c, 0x3c, 0x5c, 0xac, 0xdc,
	0x74, 0xbf, 0x6f, 0xa0, 0x34, 0x5f, 0x94, 0xb1, 0x14, 0xc8, 0x06, 0xe3, 0x5c, 0xa3, 0x31, 0xf0,
	0x29, 0x24, 0x71, 0x4a, 0x0f, 0x48, 0x87, 0xf1, 0x5c, 0xc8, 0x3b, 0x58, 0xf1, 0x41, 0x9c, 0xd5,
	0x7c, 0x08, 0x7f, 0x35, 0xf8, 0xb0, 0xe6, 0x23, 0x58, 0x6d, 0xf0, 0x51, 0xcd, 0xc7, 0xb0, 0xd6,
	0xe0, 0xe3, 0x9a, 0x4f, 0x60, 0xbd, 0xc1, 0x27, 0xf4, 0x94, 0x10, 0x3f, 0x4a, 0x52, 0xc5, 0x11,
	0x3a, 0x3e, 0xeb, 0x7a, 0xf2, 0xa8, 0x38, 0xba, 0xbd, 0x84, 0x58, 0x70, 0xd8, 0xa8, 0x56, 0x9c,
	0x0b, 0x39, 0xe5, 0xf4, 0x88, 0x6c, 0xb2, 0xcc, 0x0a, 0x5b, 0x72, 0x84, 0x4d, 0x1f, 0xd5, 0x73,
	0xfa, 0x99, 0x1c, 0xb2, 0x05, 0x13, 0x19, 0x9b, 0x89, 0x4c, 0xd8, 0x65, 0x92, 0x2a, 0x29, 0x31,
	0xb5, 0x62, 0x21, 0xec, 0x12, 0xba, 0x5e, 0x86, 0xa6, 0xf0, 0xd8, 0xc8, 0xe9, 0x15, 0xe9, 0xb7,
	0x7c, 0xe2, 0xfd, 0x16, 0xa3, 0x97, 0xce, 0x29, 0xa5, 0xd5, 0xcb, 0xb0, 0xf0, 0x9e, 0x77, 0x7a,
	0x91, 0xf9, 0xa5, 0x9f, 0x11, 0xc2, 0x99, 0x65, 0x46, 0x95, 0x3a, 0x45, 0xe8, 0x7b, 0xa1, 0x41,
	0xe8, 0x05, 0xe9, 0x71, 0x34, 0xa9, 0x16, 0x85, 0x15, 0x4a, 0xc2, 0x56, 0x78, 0x42, 0x03, 0xb9,
	0xda, 0x20, 0x2f, 0xd3, 0x24, 0xc3, 0x05, 0x66, 0xb0, 0x1d, 0x6a, 0xe3, 0xc8, 0x93, 0x03, 0xee,
	0x01, 0x98, 0x61, 0x6a, 0xb5, 0x48, 0xdd, 0x32, 0xff, 0x0e, 0x0f, 0x68, 0x20, 0x6f, 0xc8, 0x85,
	0xd0, 0x4a, 0xe6, 0x28, 0x2d, 0xec, 0x44, 0xe3, 0x15, 0xd1, 0x13, 0xd2, 0x7d, 0xd1, 0xf8, 0xb3,
	0x44, 0x99, 0x2e, 0x61, 0x10, 0xde, 0x50, 0x03, 0x3a, 0x24, 0x7b, 0x19, 0xb3, 0x6e, 0xd8, 0xae,
	0x20, 0xf5, 0xe2, 0x6e, 0xcc, 0x5a, 0xc5, 0xdb, 0x21, 0xab, 0x19, 0xb3, 0xb0, 0xeb, 0x0d, 0x37,
	0xf4, 0x44, 0x49, 0xd8, 0x8b, 0x44, 0x49, 0x4a, 0xc9, 0x9a, 0x64, 0x39, 0xc2, 0xbe, 0x47, 0x7e,
	0x4c, 0xaf, 0xc9, 0xb6, 0x2c, 0xf3, 0x24, 0xcd, 0x98, 0x31, 0x5a, 0xa9, 0xdc, 0xc0, 0x81, 0x4f,
	0xb7, 0x64, 0x99, 0x3f, 0xd6, 0xd0, 0xd5, 0xdd, 0x69, 0x19, 0xb3, 0x5a, 0x48, 0x34, 0xf0, 0x4f,
	0xd8, 0x92, 0x2c, 0xf3, 0xa7, 0x88, 0x2a, 0xc5, 0x22, 0x4b, 0xe7, 0xa8, 0x0d, 0x40, 0xad, 0xfc,
	0x88, 0xa8, 0x52, 0x8c, 0xeb, 0x15, 0x69, 0x0d, 0x1c, 0xd6, 0xca, 0x73, 0x44, 0xb5, 0xe2, 0x36,
	0xa6, 0xa4, 0x81, 0xa3, 0x57, 0x25, 0x22, 0xa7, 0x14, 0x73, 0x25, 0x31, 0x91, 0x65, 0x3e, 0x43,
	0x0d, 0xc7, 0x41, 0xf1, 0xec, 0xab, 0x47, 0xf4, 0x9c, 0xf4, 0x0a, 0x65, 0x2c, 0xcb, 0x42, 0x97,
	0x9c, 0x84, 0x26, 0x08, 0xc8, 0x37, 0xc9, 0x07, 0x42, 0x4d, 0x81, 0xc8, 0xdb, 0xf5, 0x3d, 0xf5,
	0xde, 0xc0, 0x27, 0xad, 0xea, 0xde, 0x92, 0x81, 0x5d, 0x16, 0xd8, 0xb6, 0xcf, 0xbc, 0xbd, 0xe3,
	0x82, 0x96, 0x7c, 0x4e, 0x7a, 0x5e, 0x0e, 0xb7, 0x06, 0x9c, 0x87, 0x97, 0x3b, 0x14, 0x2f, 0x8a,
	0x3d, 0xb2, 0xfe, 0x8b, 0x59, 0xd4, 0x70, 0xe1, 0xa3, 0x30, 0x71, 0x5d, 0x97, 0x6a, 0x64, 0x16,
	0x79, 0xc2, 0x2c, 0x5c, 0x86, 0x9e, 0x88, 0xe4, 0xc1, 0xba, 0xb8, 0x2c, 0x78, 0x15, 0x5f, 0x85,
	0x38, 0x92, 0x07, 0xeb, 0x0e, 0x6c, 0xa1, 0xd5, 0x0c, 0xdd, 0x81, 0xfd, 0x37, 0x1c, 0x58, 0x3f,
	0x9f, 0x72, 0xf7, 0x89, 0x43, 0x54, 0x68, 0xb5, 0x10, 0x1c, 0x35, 0xfc, 0x17, 0x3e, 0xb1, 0xa7,
	0xdf, 0x22, 0xa4, 0xfb, 0xa4, 0x23, 0x4c, 0xe1, 0xfe, 0x7f, 0x1d, 0x96, 0x25, 0x4c, 0x31, 0xe5,
	0xf4, 0x98, 0x74, 0xc3, 0x46, 0x5c, 0xf2, 0x7f, 0x38, 0xef, 0x01, 0x4c, 0x39, 0x1d, 0x90, 0x35,
	0xc1, 0x93, 0x3b, 0x78, 0x13, 0x9a, 0x4c, 0xf0, 0xbb, 0x88, 0x86, 0x70, 0x53, 0xa1, 0x61, 0x44,
	0x23, 0x78, 0x5b, 0xa1, 0x51, 0x44, 0x63, 0x78, 0x57, 0xa1, 0x71, 0x44, 0x13, 0xb8, 0xad, 0xd0,
	0x24, 0xa2, 0x7b, 0x78, 0x5f, 0xa1, 0xfb, 0x59, 0xc7, 0xdf, 0xbe, 0xe3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x96, 0x0a, 0x76, 0x91, 0x94, 0x05, 0x00, 0x00,
}
